### ISSUE TITLE
Task: Content Editing

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-co-nz#8]
Make sure that all the needed content is authored.

**Comment by manuel-vara** [comment]
@Kannan-CM please create the sections and content.

**Comment by girishdigrajkar** [comment]
Hi @Kannan-CM , Varun,

**Macktrucks.co.nz  observations :**

1. View all Trucks does not show submenu navigation 
2. Find my dealer is not integrated                                            ****. Final dealer list not available from Volvo
3. Clicking on Login icon navigates to [mactrucks.com](http://mactrucks.com/) which is not expected 
4.  Truck pages / sub navigation menu is not available 
5. Experience tab has no links authored/ ( except ‘careers’, ‘Offer & Incentives’ no links are authored)
6. https://main--vg-macktrucks-co-nz--hlxsites.hlx.page/buy-mack/request-a-quote/  is not authored
7. https://main--vg-macktrucks-co-nz--hlxsites.hlx.page/powertrain-and-suspensions/engines/  read more button is not authored
8. Parts & Services tab >>  Parts >> Except ‘Parts Overview’ rest of the links are not authored
9. Parts & Services tab >>  Integrated Uptime  >> Except ‘Uptime Solutions’ other links are not authored
10. Parts & Services tab >>  Fleet Services >> All links are not authored
11. Parts & Services tab >>  Support >> All links are not authored
12. Trucks >> Mack Lineup >> Except ‘Mack Anthem’ non of the truck pages are authored
13. Trucks >> POWERTRAIN >>  Axles, Suspensions & Exhaust Aftertreatment Systems  pages are not authored
14.  Home page >> Community section links takes user to AU links instead of NZ links
15. Footer links are not authored e.g. Mack News, Change Country, Body Builder , 2023 Labor Negotiations, SDS info, Emmision info & Contact us

**Comment by DanielaPedrochevd** [comment]
@Kannan-CM is this ticket done? can we close it? please let us know before the end of the day.

**Comment by Kannan-CM** [comment]
Content To be updated by Wednesday
